### ISSUE TITLE
ping-pong test, connect(), and lack of error messages

### ISSUE THREAD

**Issue by LeeTibbert** [armanbilge/epollcat#19]
Discovered in the TcpSuite `server-client ping-pong` test, but probably generally applicable.

`connect(foo)` needs to give some indication of error, perhaps `Throw`ing
when the connection fails.

Later:  
I see that  `/EpollAsyncSocketChannel.scala` has two places
where it throws `ConnectException("Connection refused")`.
If I can create time, I will have to check why those did not
trigger.

The problem may be that it does so currently and that something in the
peer-to-peer test is not letting that message propagate to the user.

**Comment by LeeTibbert** [comment]
Later:  Debugging writes reveal that a proper & expected ConnectException is being thrown
about line 236 in `EpollAsyncSocketChannel.scala` and never showing up to interrupt the 
test or even being reported.

More later, shift over.

**Comment by armanbilge** [comment]
Is this issue resolved as of https://github.com/armanbilge/epollcat/pull/31?

**Comment by LeeTibbert** [comment]
Yes it is.  Thank you for that fix and this bookkeeping

For the future: 
 Resolution is that the ConectException _was_ being thrown but it took 2 minutes or so
for the TCP SYN connection handshake to timeout and then throw. That Exception
was then being ignored by the test, making it look like the ConnectException never 
happened.
