### ISSUE TITLE
macOS support via `kqueue`

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/epollcat#2]
Blocked by:
- https://github.com/scala-native/scala-native/issues/2802

**Comment by armanbilge** [comment]
This is now unblocked as of SN 0.4.6.

https://scala-native.readthedocs.io/en/latest/changelog/0.4.6.html

**Comment by LeeTibbert** [comment]
I will take a look at implementing this.  

Labor Day long weekend in the US, so it may take me a few
days to start. 

If anybody else gets there first, please let me know.

**Comment by armanbilge** [comment]
Sorry @LeeTibbert, I'm going to make start on this 😜

**Comment by LeeTibbert** [comment]
Devil take the hindmost.  Thank you for the update.  Glad that you are getting to it.

As always, let me know if you want me to try something on my mac M1.
