### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/epollcat#3]
~IPv6 is badly broken in Scala Native 0.4.x, but is already fixed in the 0.5.x. Our options are to:~
1. ~roll our own bindings instead of using `scalanative.posixlib`~
2. ~wait it out until 0.5.x~

Update: seems that IPv6 was broken only in Javalib, the actual Posix bindings should be working. This makes this issue actionable 🚀

**Comment by LeeTibbert** [comment]
> IPv6 is badly broken in Scala Native 0.4.x, but is already fixed in the 0.5.x.

Arman, 
To help the epollcat along, I will check when I fixed what and refresh my
memory of what is in what soup pot.  

To the best of my memory, `posixlib` IPv6 should be working well. 
I seem to remember that there were some missing UDP (Datagram)
methods in the 0.4.x stream.   

When I added them, I specifically created unit-test Udp6*Test.scala 
files.  I am not entirely test-driven-design, but I have found that at least
a first draft of the Tests pays off and focuses my implementation.

If you experience any IPv6 related problems with `posixlib` IPv6
methods/routines please let me know soonest & loudest.

What _is_ broken in the 0.4.x stream is the `javalib` IPv6 support.
In 0.4.x (and probably 3.x and back to 2.x) there are bits and
pieces which lead one to think that IPv6 is supported, but
there are show-stopper "end-of-implementation" issues.

It took me 2+ weeks or so to get it working in my sandbox.

The shells on the board move around:  if your concern is indeed javalib, let me know.   

I will let it sit on the back of my brain to think if there is anything epollcat for SN can do 
to workaround SN 0.4.n javalib IPv6 breakage.

**Comment by armanbilge** [comment]
@LeeTibbert thanks for that helpful comment. It seems I may have misunderstood what the support/limitations of IPv6 in SN 0.4.x are.

Note that epollcat is directly interfacing with posixlib and is not using Javalib. So if we can make ipv6 work here on 0.4.x that would be fantastic!

I was under the impression that fixing IPv6 in Javalib required breaking changes to posixlib since you targeted that work at 0.5.x. Which would lead me to think that it is somehow broken in posixlib as well. But I'd be happy to be wrong.

I may have stumbled on some IPv6 issues while developing epollcat, I will look through the commit history and see if I can refresh my memory.

**Comment by LeeTibbert** [comment]
> So if we can make ipv6 work here on 0.4.x that would be fantastic!
I think that it is there & silently doing its job, without complaint.  It is always the Good Child
who get passed over for the Prodigal.

Later:  Now some of it comes back to me. I think there was an IPv6 related problem with
two UDP methods. I can check the Repository change log to figure out exactly which ones.
I think they were the simple `sendmsg()/readmsg()` pair.  I discovered the bug in my
testing but never heard a field report. 

I am learning epollcat on the fly and am still in the early stages.  I suspect that users
of epollcat can pass in any kind of socket descriptor from a socket previously created
by the caller.  In that case, the breakage would be users using both IPv6 and UDP.
Before we call the fire department, let me check the commit history.

>  was under the impression that fixing IPv6 in Javalib required breaking changes to posixlib

I just went back to the primary source for grounding, the pending IPv6 javalib PR. 
There was small change to a posixlib file `socket.c`. That was to a Windows only code path.

The 'breaking change' to provide IPv6 in 0.4.n is basically a useful fiction:

1) I really do not want to be forcing that big of a change on people when
    they upgrade a minor version.  Especially when the only "opt-out" is
    to downgrade the version.  I know that I as an application developer or
   end user would be livid or beyond if that happened and I had problems:
   like a Friday-before-holiday hard broken application.  I try to live my
   life in Joy and not Fear, but Fear brings some good lessons.

2) I am pretty confident with the 0.5.0 javalib IPv6 changes but I would
    like to see them get some clock, or better yet, calendar time being
    used in the Wild. 

> I may have stumbled on some IPv6 issues while developing epollcat, I will look through the commit history
> and see if I can refresh my memory.

I try to find issues before they ship. Each new environment reveals a new class of bugs,
no matter what the software.  So, you find them, I fix them (if possible) tag-team.

**Comment by LeeTibbert** [comment]
channels, very timely, this morning's discussion.

To the best of my knowledge & belief, SN has no channel support
for any `java.net` class; not (TCP or streaming) `Socket` & `ServerSocket`.
The Datagram class is entirely un-implemented. It is a dream rapidly
receding in my rear-view mirror. 

Pardon my over-extended brain and lack of epoll knowledge.  How can
a (application developer) user currently ever get a network related channel
to pass to epoll?

It sounds like the (broken on IPv6) javalib routines are making the network calls,
probably by calling into posixlib.  It is the javalib layered where the 0.4.n breakage
happens.

**Comment by armanbilge** [comment]
@LeeTibbert you may find it informative to look at the test suite:

https://github.com/armanbilge/epollcat/blob/91a0401f49a94ce8c31849a71482aa54949cfa73/tests/shared/src/test/scala/epollcat/tcp/TcpSuite.scala

> Pardon my over-extended brain and lack of epoll knowledge. How can
a (application developer) user currently ever get a network related channel
to pass to epoll?

That's the point: the application developer doesn't pass anything to epoll, indeed they don't even need to know that's how it's working under the hood. They just use the Javalib as normal and the `EpollRuntime.global` as their `ExecutionContext`. Everything just works.

If you want to look further, I also have the fs2-io `SocketSuite` passing with the implementations from epollcat.

https://github.com/typelevel/fs2/blob/3d25a6a1723d160afba2a961fc0cfe17aca8cbe9/io/shared/src/test/scala/fs2/io/net/tcp/SocketSuite.scala

**Comment by LeeTibbert** [comment]
OK, `TcpSuite.scala` give me something concrete to look at.

I checked and `postman-echo.com` only has IPv4 addresses (and 
three of them).  So this test should work until postman.com
becomes contemporary.

The discussion below is for people in the Wild who may attempt
to use epollcat with IPv6 addresses (like me).

I am still digesting it. From my reading I would expect this to be hard broken with IPv6 on 
both 0.4.7 and 0.5.0-SNAPSHOT-2022-09-02.

My IPv6 PR has not been merged.  I would hope and be gratified if this worked with that PR.
I can take another look at the example program to see if that would be easier to hack to
use a known IPv6 address.   My favorite is `https://www.kame.net/` (should see dancing/swimming
kame).   Now parsing the html returned might take some work.  Probably first start off checking if
a connection happens. Second pass, parse one header.

 I think it is worth waiting, say two weeks, until the IPv6 PR merges (or is rejected).
That would give us 0.5.0-SNAPSHOT as opposed to 0.5.0-OfCourseItWorksInDevosEnvironment.

**Comment by LeeTibbert** [comment]
I think it is well worthwhile to amend the base note to say that javalib IPv6 is broken and not
the posixlib currently mentioned.

**Comment by armanbilge** [comment]
@LeeTibbert I'm afraid I'm still confused :)

epollcat doesn't use SN Javalib for any IPv6 support. It uses only posixlib. If I understand you correctly, posixlib IPv6 is not broken. So is this statement still correct?

> From my reading I would expect this to be hard broken with IPv6 on both 0.4.7

**Comment by armanbilge** [comment]
@LeeTibbert and I had a productive chat about this issue. They are going to look into adding IPv6 support to epollcat 🎉

**Comment by LeeTibbert** [comment]
First IPv6 Scala Native 0.4.5 result:
```  
  + server-client ping-pong
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
```
Looks indistinguishable from Java IPv6 and ScalaJVM IPv4.
I had to use specialist tools to prove to myself that it _was_  IPv6.

Long way to go, but looks like there is a way through.

**Comment by armanbilge** [comment]
Amazing!! Thanks for the update!!

**Comment by armanbilge** [comment]
I am concerned that this issue is becoming more urgent. I suspect it is related to:
- https://github.com/armanbilge/epollcat/issues/43
- https://github.com/typelevel/fs2/pull/2975#issuecomment-1242964149

**Comment by LeeTibbert** [comment]
As a marker and to summarize a number of discussions in Issue #43 and elsewhere,
I am switching to evolving my IPv6 rapid-prototyping code into a Work in Progress (WIP) PR.

That will give a concrete platform for working on the next evolution of issues.

**Comment by LeeTibbert** [comment]
:rocket:
