### ISSUE TITLE
Chance to simplify TcpSuite ping-pong

### ISSUE THREAD

**Issue by LeeTibbert** [armanbilge/epollcat#30]
We are chasing more important errors in TcpSuite ping-pong.

Whilst chasing those, I noticed the lines in the client side
```
  _ <- IO(
            assert(clue(clientLocalAddr.asInstanceOf[InetSocketAddress].getPort()) != 0)
```
Does that tell us anything we do not already know, or that the writes immediately
below will not complain about.  I have a hard time imagining how `connect()` could
succeed without setting a localAddress.   Perhaps this was early development
time only belt-and-suspenders implementation insurance code?

**Comment by armanbilge** [comment]
Yes, belt-and-suspenders I think 😆 we now have a better test for this here I believe:

https://github.com/armanbilge/epollcat/blob/f87cccc976c43fb0693ec4a56e9c59b9215b1d2c/tests/shared/src/test/scala/epollcat/TcpSuite.scala#L169-L187

**Comment by LeeTibbert** [comment]
Yes, this is a better test.

By my reading this is OK, because the ServerSocket is listening(), as part of pseudo-JVM bind(),
and the client connection can happen as long as there is only a short pause before the accept.
I would have to check what the definition of "short" is: seconds?
