### ISSUE TITLE
UnsupportedPlatformError appears missing in Scala Native in both 'main' and 'macos' branches

### ISSUE THREAD

**Issue by LeeTibbert** [armanbilge/epollcat#36]
Fresh clone into empty directory, approximately Friday. 2022-09-09 19:00 EDT

`sbt> test`  or `sbt:root> testsNative/test`  (as one would expect).

```info] Optimizing (debug mode) (1655 ms)
[error] Found 2 missing definitions while linking
[error] Not found Top(epollcat.UnsupportedPlatformError)
[error] Not found Member(Top(epollcat.UnsupportedPlatformError),RE)
[error] 	at /Users/Mumble/core/src/main/scala/epollcat/unsafe/EventPollingExecutorScheduler.scala:37

```
Found on macOS M1, Monterrey, but I expect it is common to all architectures & operating systems.

Thank you for the opportunity to take a break.

**Comment by armanbilge** [comment]
Huh, thanks for reporting this. This is concerning.

>  but I expect it is common to all architectures & operating systems

Why do you expect this? It seems to be working in macOS CI in https://github.com/armanbilge/epollcat/pull/27 as well as my local macOS intel machine.

So I wonder if somehow there is an issue with M1 specifically? If you may a program that prints the value and `LinktimeInfo.isMac` what are your results?

**Comment by armanbilge** [comment]
Sorry, I may have misunderstood: is this on the `main` branch? That is the expected result until the macOS PR merges. What is the exact commit?

**Comment by LeeTibbert** [comment]
Yes, I just triple-checked `main`.   If this error is expected there,
I will ignore the surprise.  Life on the bleeding edge...

I also saw in when I cleaned, then checked out `remotes/origin/pr/macos`
Given your information, I am spending time ensuring that I am indeed
on the `macos` branch.  I am seeing the same error.   

Just so that I know what I am chasing, does the true macOS branch
still throw errors when more than one test is done? Asking in case
I missed a zig, zag, or improvement.

```
commit 03ba035a1c6ae552ea30e7c67af493d59e0deca2 (HEAD -> main, origin/main, origin/HEAD, remotes/origin/pr/macos)
Merge: 9fb9929 c213e3f
Author: Arman Bilge <armanbilge@gmail.com>
Date:   Thu Sep 8 10:29:39 2022 -0700

    Merge pull request #34 from armanbilge/update/munit-cats-effect-2.0.0-M2
    
    Update munit-cats-effect to 2.0.0-M2
```

**Comment by armanbilge** [comment]
Thanks for the update Lee and checking these again 😕 

> Just so that I know what I am chasing, does the true macOS branch
still throw errors when more than one test is done?

Hmm, no the macOS branch should not be throwing any more errors. It should pass CI cleanly. Are you continuing to see stack traces?

**Comment by LeeTibbert** [comment]
re: stacktraces     I am never getting beyond the "UnsupportedPlatform" exception.  

I deleted that entire directory and am just about to do a fresh clone into a new, clean directory.
I will ignore the 'main' branch and convince myself that I am on the macos branch.  I suspect
that I am generating confusion through a mis-step on my part.

**Comment by LeeTibbert** [comment]
Building & running (multiple) tests on `macos` works now. 
I must have messed up my environment in re-fetching.

I fell off the trail with the `UnsupportedPlatformError` on
`main`.  Now I understand that is a "not yet there" 
inconsistency.

Thank you for the quick turn around.
