### ISSUE TITLE
Error codes from getaddrinfo could be translated.

### ISSUE THREAD

**Issue by LeeTibbert** [armanbilge/epollcat#39]
`gai_strerror() ` could be to translate the code returned upon failure from `getaddrinfo`.
Unlike errno codes, these error codes are hard to lookup on the web.

**Comment by LeeTibbert** [comment]
@armanbilge  
Thank you for the go-ahead.

I see the preferred scalafmt version in `.scalafmt.conf`.  From `project/plugins.sbt` it appears
that you run scalafmt from the command line (in the project root)?  True?

Thanks.

**Comment by armanbilge** [comment]
@LeeTibbert yes that's correct, you can run `sbt scalafmtAll`. It should also work to run the scalafmt CLI if you have it installed on your system.

**Comment by LeeTibbert** [comment]
Code all nice and tidy now, thanks.

I used the `sbt scalafmtAll`, the one I had been hoping for.
I did not see a plugin for in in `build.sbt` or `project/*.sbt`.
What is the magic that enables it?  I would like to crib that.

**Comment by armanbilge** [comment]
This project uses the sbt-typelevel plugin, which automatically loads several plugins (including sbt-scalafmt). It also generates the CI workflows and sets up publishing, etc. etc. :)

https://typelevel.org/sbt-typelevel/
