### ISSUE TITLE
Check for IPv6 support at runtime/startup

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/epollcat#52]
As Lee proposes in https://github.com/armanbilge/epollcat/pull/50#discussion_r969068300.

**Comment by LeeTibbert** [comment]
My brain is in SN InetAddress right now. How about I start fresh on this tomorrow
morning.  

Getting this moving will have the advantage of exercising the now merged IPv6 code.
The only side-effect should be a tiny slowdown at first use of a socket.  

Perhaps you could PM me a few of your favorite sites and I can see
if they have IPv6 addresses.  

The initialization code parses the
numeric host and checks for an active IPv6 non-loopback network
interface.  It does not do a possibly time consuming trip out
to the name server and back.

The designer in me wishes that there were some way to 
query SN and follow its lead.   Perhaps  fixing the
immediate problem is a less-than-ugly way, and letting
the desire for elegance brew for a while. Creativity may
arise.
