### ISSUE TITLE
EpollAsyncServerSocketChannel#bind(null) should use wildcard, not give NPE

### ISSUE THREAD

**Issue by LeeTibbert** [armanbilge/epollcat#63]
The Java spec for ServerSocketChannel#bind(null) states that a null argument
should use an address of Java's choice.  The JVM appears to use the wildcard
address for the underling implementation socket '0.0.0.0' or "::0" (expanded).
I believe there is a description else where which directs the use of wildcard.

I believe this is architecture and os version independent.  

Code in `EpollAsyncServerSocketChannel#bind` should be relatively
easy to fix.

**Comment by armanbilge** [comment]
Using a wildcard seems reasonable. Note that FS2 will never pass a null value here, but being compliant here is easy.

**Comment by LeeTibbert** [comment]
> Using a wildcard seems reasonable. Note that FS2 will never pass a null value here, but being compliant here is easy.

Good to know the context. Thank you  

Some weenie writing test code might pass a null ;-)  I discovered this by trying to use it
with its JVM described parent AsynchMumble.

In general Scala code I have little patience for people passing null's around. However,
on the edge of Scala & JVM I am forced to be a little more accomodating.  I will
put this on the "someday" pile,

**Comment by LeeTibbert** [comment]
I note for future reference that the C getaddrinfo specification & practice is to treat 
a null nodename as equivalent to localhost.
