### ISSUE TITLE
Binding to wildcard "0.0.0.0" then connecting throws `ConnectException` on macOS

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/epollcat#92]
Reproducer in https://github.com/armanbilge/epollcat/commit/6c3ea7e77bf9ddb901983d434655546ce1ac414a.

https://github.com/armanbilge/epollcat/blob/6c3ea7e77bf9ddb901983d434655546ce1ac414a/tests/shared/src/test/scala/epollcat/TcpSuite.scala#L244-L254

**Comment by armanbilge** [comment]
On my macOS 11 machine the `println` above gives met this:
```
/0:0:0:0:0:0:0:0:60833
```
(the port number varies per-run)

Furthermore, if I change the `connect(...)` to this:
```scala
connect(new InetSocketAddress("0.0.0.0", addr.asInstanceOf[InetSocketAddress].getPort))
```

Then the test passes.

@LeeTibbert could this be another case of getting an IPv4-compatible address instead of an IPv4-mapped address?

**Comment by LeeTibbert** [comment]
>  could this be another case of getting an IPv4-compatible address instead of an IPv4-mapped address?

Arman,  I think you have it exactly!   

I will have to trace through the code.   When I did the PR to the similar issue I let 
::0 pass without conversion because that is the IPv6 wildcard.   I have to dive
into the `InetSocketAddress("0.0.0.0", 0)` construction path to see how it
picks up its interior InetAddress.

**Comment by LeeTibbert** [comment]
Arman,

I've spent a long morning tracing this and think I have an understanding of two of the things, plural,
going wrong.  I need to write some C to track down a third. I also need to check how SN handles
a translation.

Overnight I will work on coming up with a good description of "what", then we can work out 
possible solutions.   Not to keep you hanging but any description I write now would be gibberish
and cause more confusion.

**Comment by LeeTibbert** [comment]
Progress but no solution, then again, one can progress around a ring and not
get to the end.

I ratted around and found a python IPv6 client/server pair that I had been using
last Summer (2022).  Adapted them to this Issue and fired them up on Linux. All worked.
I then fired them up on macOS 13.0.mumble. Everything worked. Rats! I had been
expecting a connection to ::0 to fail on macOS.  The both server programs reported
that the connection came in on ::1, which is sensible.

Thinking that python might be "helping" me under the covers, I cobbled together
a C client/server pair which suits this issue.  Ran on Linux, everything passed, as expected.
Ran on macOS, and everything passed. Double Rats!!   Strange situation where something
working is cause for dismay.

I think the code thru the server is doing a sensible thing (but plenty of room for discussion later).
I need to look more closely at the connect code and trace through, knowing that connecting 
to ::0, strange as it might be, works in python and C.

More as I discover it.  Time consuming as it is, I am glad you discovered this issue.

**Comment by armanbilge** [comment]
Thanks for the update :) I also ratted around in Node.js and libuv, and am hitting the same wall. Surely some other implementation has encountered these "quirks" and taken defensive measures, but I'm yet to stumble on it.

However, being unable to reproduce in a C implementation ... is interesting and unexpected 😅  is there any possibility that Scala Native is doing _something_ during startup/initialization that could lead to this? It would explain why a vanilla C implementation behaves differently.

**Comment by LeeTibbert** [comment]
I believe the simple C programs worked and epollcat revealed the underlying OS failure/behavior
is because the former were written to block until the `connect()` completed and epollcat is async.

More next sprint, when my mind has untangled.

**Comment by armanbilge** [comment]
Thanks for the detailed write-up. Suffice to say, it's taken me more than a few passes for ~~all~~ most of it to sink in :)

I think we can all agree that a large part of the problem is the early allocation of the socket file descriptor, before we know whether we want AF_INET or AF_INET6. I blame the poor design of the JDK in this area which leaves us in a bad position. I am not sure if either of proposals has semantics that match the JDK, which would make it difficult to use in cross-compiling code. The real answer is, implement a different (better) API.

Something that bugs me is what feels like an  "asymmetry": specifically, that you can bind a socket to `0.0.0.0`/`::0`, but if you get the local address of said socket and attempt to connect to it, it is undefined behavior. What good is a local address if you cannot connect to it?

**Comment by LeeTibbert** [comment]
Linux & macOS IPv4 obviously agree with you (as do I).   

A lot turns on "get the local address of said socket".
The situation comes about because of the interaction of two "magic" items: "Any" address & bind changing
its own socket address.  IPv6 is pretty strict about ::0 "Any" only making sense as an object for a server bind.
There is some room for discussion that "get local socket address" on a socket bound to ::0 should return
::1. (and that bind() should be changing its InetSocketAddress() to the same -- injecting mutability).  

Rolling the discussion __way__ back, connect(0.0.0.0) & connect(::0) should both be rejecting the connection
as "connect to any address" makes no sense.  That horse left the gate a long time ago.

Life in network land.
